version: "3.8"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
      POSTGRES_DB: fastapi_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Aquí almacenaremos los datos localmente
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: dockerfile.dev  
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com #Correo para iniciar sesión pgadmin
      PGADMIN_DEFAULT_PASSWORD: admin #Contraseña pra iniciar sesión pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:  # Define el volumen para PostgreSQL

